# Generated by Django 3.2.3 on 2024-01-26 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='times_used',
            field=models.IntegerField(default=0, verbose_name='Количество использований продукта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='products',
            field=models.ManyToManyField(through='recipes.RecipeProduct', to='recipes.Product', verbose_name='Продукты в рецепте'),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe', verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='recipeproduct',
            name='weight',
            field=models.IntegerField(verbose_name='Вес продукта в рецепте'),
        ),
    ]
