# Generated by Django 5.0.1 on 2024-01-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0003_alter_product_times_used"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterModelOptions(
            name="recipe",
            options={"verbose_name": "рецепт", "verbose_name_plural": "Рецепты"},
        ),
        migrations.AlterModelOptions(
            name="recipeproduct",
            options={
                "verbose_name": "продукт в рецепте",
                "verbose_name_plural": "Продукты в рецептах",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="times_used",
            field=models.IntegerField(
                default=0, verbose_name="Количество использований продукта"
            ),
        ),
    ]
