# Generated by Django 3.2.3 on 2024-01-29 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_alter_product_options_alter_recipe_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipeproduct',
            unique_together={('recipe', 'product')},
        ),
    ]
